version: '3'

services:

  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    networks:
      - gogs-backend
    volumes:
      - ~/workspace/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=gogs
      - MYSQL_USER=rajesh
      - MYSQL_PASSWORD=pass

  gogs:
      image: gogs/gogs
      depends_on:
        - mysql
      restart: always
      ports:
        - 10080:3000
        - "10022:22"
      networks:
        - gogs-backend
      volumes:
        - ~/workspace/gogs:/data

networks:
  gogs-backend:
    driver: bridge
